### ISSUE TITLE
GHC eventlog based stats todo list

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/haskell-perf#7]
Changes to GHC, higher pri:

* [x] Use perf counters in the user defined window as well
* [x] Add a precise allocation counter
* [ ] Add a OS process level CPU counter as well to account for entire program time, this counter should not be stopped during the entire window. This would be a window only counter.
* [ ] flush the event log buffer before and after the thread run if beyond halfway mark

Changes to GHC, Lower pri:

* [ ] Add more relevant perf counters (esp. HW events)
* [ ] Add pinned allocations, unpinned allocations, and large allocations counters
* [ ] Enable the counter measurement code only when `+RTS -l` is specified (put code under eventlog_enabled)
* [ ] Put the code under ifdef `LINUX_PERF_EVENT`
* [ ] traceEventIO adds a lot of allocations, see if we can reduce that
* [ ] Use a unique id for each start/stop event pair for better correlation in case an event is missed
* [ ] Select the enabled counters via RTS options
* [ ] Support multiple counters at the same time
* [ ] Select a particular thread label to trace, to reduce eventlog traffic
* [ ] Select to log only the perf events

Changes to the eventlog parser:

* [ ] Print periodically e.g. every second instead of on each event
* [ ] Print after collecting `n` events
* [ ] activate a window across all threads, account the time of all haskell threads during the window
